---
homebrew_taps:
  - aws/tap

homebrew_cask_apps:
  - 1password
  - docker
  - dotnet-sdk
  - google-chrome
  - iterm2
  - microsoft-teams
  - royal-tsx
  - slack
  - visual-studio-code

homebrew_installed_packages:
  - aws-sam-cli
  - awscli
  - azure-cli
  - csvkit
  - dive
  - gh
  - grpcurl
  - jinja2-cli
  - jq
  - kubernetes-cli
  - neofetch
  - python@3.10
  - volta
  - wget
